//====================================================================================================
// Base code generated with Inertia: BE Gen (Build 2.5.5049.15162)
// Layered Architecture Solution Guidance (http://layerguidance.codeplex.com)
//
// Generated by Administrator at SAPSERVER on 12/31/2014 17:24:16 
//====================================================================================================

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Linq;
using System.Runtime.Serialization;


namespace SBiPayrollWeb.Entities
{
    /// <summary>
    /// Represents a row of Employee_Ext data.
    /// </summary>
    [Serializable]
    [DataContract]
    public partial class Employee_Ext
    {
        /// <summary>
        /// Gets or sets a string value for the EmpNo column.
        /// </summary>
        [DataMember]
        [Browsable(false)]
        public string EmpNo { get; set; }

        /// <summary>
        /// Gets or sets a int value for the ExFieldName column.
        /// </summary>
        [DataMember]
        [Browsable(false)]
        public int ExFieldName { get; set; }

        /// <summary>
        /// Gets or sets a string value for the ExFieldStr column.
        /// </summary>
        [DataMember]
        public string ExFieldStr { get; set; }

        /// <summary>
        /// Gets or sets a int value for the ExFieldInt column.
        /// </summary>
        [DataMember]
        public int ExFieldInt { get; set; }

        /// <summary>
        /// Gets or sets a DateTime value for the ExFieldDate column.
        /// </summary>
        [DataMember]
        public DateTime ExFieldDate { get; set; }

        /// <summary>
        /// Gets or sets a decimal value for the ExFieldDecimal column.
        /// </summary>
        [DataMember]
        public decimal ExFieldDecimal { get; set; }
    }
}
