//====================================================================================================
// Base code generated with Inertia: BE Gen (Build 2.5.5049.15162)
// Layered Architecture Solution Guidance (http://layerguidance.codeplex.com)
//
// Generated by Administrator at SAPSERVER on 12/31/2014 17:24:16 
//====================================================================================================

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Linq;
using System.Runtime.Serialization;


namespace SBiPayrollWeb.Entities
{
    /// <summary>
    /// Represents a row of Payroll data.
    /// </summary>
    [Serializable]
    [DataContract]
    public partial class Payroll
    {
        /// <summary>
        /// Gets or sets a int value for the Period column.
        /// </summary>
        [DataMember]
        [Browsable(false)]
        public int Period { get; set; }

        /// <summary>
        /// Gets or sets a int value for the Year column.
        /// </summary>
        [DataMember]
        [Browsable(false)]
        public int Year { get; set; }

        /// <summary>
        /// Gets or sets a int value for the EmployerId column.
        /// </summary>
        [DataMember]
        public int EmployerId { get; set; }

        /// <summary>
        /// Gets or sets a DateTime value for the DateRun column.
        /// </summary>
        [DataMember]
        public DateTime DateRun { get; set; }

        /// <summary>
        /// Gets or sets a string value for the RunBy column.
        /// </summary>
        [DataMember]
        public string RunBy { get; set; }

        /// <summary>
        /// Gets or sets a bool value for the Approved column.
        /// </summary>
        [DataMember]
        public bool Approved { get; set; }

        /// <summary>
        /// Gets or sets a string value for the ApprovedBy column.
        /// </summary>
        [DataMember]
        public string ApprovedBy { get; set; }

        /// <summary>
        /// Gets or sets a bool value for the IsOpen column.
        /// </summary>
        [DataMember]
        public bool IsOpen { get; set; }

        /// <summary>
        /// Gets or sets a bool value for the Processed column.
        /// </summary>
        [DataMember]
        public bool Processed { get; set; }
    }
}
