//====================================================================================================
// Base code generated with Inertia: BE Gen (Build 2.5.5049.15162)
// Layered Architecture Solution Guidance (http://layerguidance.codeplex.com)
//
// Generated by Administrator at SAPSERVER on 12/31/2014 17:24:16 
//====================================================================================================

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Linq;
using System.Runtime.Serialization;


namespace SBiPayrollWeb.Entities
{
    /// <summary>
    /// Represents a row of PayslipMaster_Temp data.
    /// </summary>
    [Serializable]
    [DataContract]
    public partial class PayslipMaster_Temp
    {
        /// <summary>
        /// Gets or sets a int value for the Period column.
        /// </summary>
        [DataMember]
        [Browsable(false)]
        public int Period { get; set; }

        /// <summary>
        /// Gets or sets a int value for the Year column.
        /// </summary>
        [DataMember]
        [Browsable(false)]
        public int Year { get; set; }

        /// <summary>
        /// Gets or sets a string value for the EmpNo column.
        /// </summary>
        [DataMember]
        [Browsable(false)]
        public string EmpNo { get; set; }

        /// <summary>
        /// Gets or sets a int value for the EmployeeId column.
        /// </summary>
        [DataMember]
        public int EmployeeId { get; set; }

        /// <summary>
        /// Gets or sets a DateTime value for the PaymentDate column.
        /// </summary>
        [DataMember]
        public DateTime PaymentDate { get; set; }

        /// <summary>
        /// Gets or sets a string value for the PrintedBy column.
        /// </summary>
        [DataMember]
        public string PrintedBy { get; set; }

        /// <summary>
        /// Gets or sets a DateTime value for the PrintedOn column.
        /// </summary>
        [DataMember]
        public DateTime PrintedOn { get; set; }

        /// <summary>
        /// Gets or sets a string value for the EmpName column.
        /// </summary>
        [DataMember]
        public string EmpName { get; set; }

        /// <summary>
        /// Gets or sets a string value for the PayPoint column.
        /// </summary>
        [DataMember]
        public string PayPoint { get; set; }

        /// <summary>
        /// Gets or sets a string value for the PIN column.
        /// </summary>
        [DataMember]
        public string PIN { get; set; }

        /// <summary>
        /// Gets or sets a string value for the NHIFNo column.
        /// </summary>
        [DataMember]
        public string NHIFNo { get; set; }

        /// <summary>
        /// Gets or sets a string value for the NSSFNo column.
        /// </summary>
        [DataMember]
        public string NSSFNo { get; set; }

        /// <summary>
        /// Gets or sets a string value for the Department column.
        /// </summary>
        [DataMember]
        public string Department { get; set; }

        /// <summary>
        /// Gets or sets a string value for the EmpGroup column.
        /// </summary>
        [DataMember]
        public string EmpGroup { get; set; }

        /// <summary>
        /// Gets or sets a string value for the EmpPayroll column.
        /// </summary>
        [DataMember]
        public string EmpPayroll { get; set; }

        /// <summary>
        /// Gets or sets a string value for the CompName column.
        /// </summary>
        [DataMember]
        public string CompName { get; set; }

        /// <summary>
        /// Gets or sets a string value for the CompAddr column.
        /// </summary>
        [DataMember]
        public string CompAddr { get; set; }

        /// <summary>
        /// Gets or sets a string value for the CompTel column.
        /// </summary>
        [DataMember]
        public string CompTel { get; set; }

        /// <summary>
        /// Gets or sets a decimal value for the PayeTax column.
        /// </summary>
        [DataMember]
        public decimal PayeTax { get; set; }

        /// <summary>
        /// Gets or sets a decimal value for the BasicPay column.
        /// </summary>
        [DataMember]
        public decimal BasicPay { get; set; }

        /// <summary>
        /// Gets or sets a decimal value for the Benefits column.
        /// </summary>
        [DataMember]
        public decimal Benefits { get; set; }

        /// <summary>
        /// Gets or sets a decimal value for the Variables column.
        /// </summary>
        [DataMember]
        public decimal Variables { get; set; }

        /// <summary>
        /// Gets or sets a decimal value for the OtherDeductions column.
        /// </summary>
        [DataMember]
        public decimal OtherDeductions { get; set; }

        /// <summary>
        /// Gets or sets a decimal value for the GrossTaxableEarnings column.
        /// </summary>
        [DataMember]
        public decimal GrossTaxableEarnings { get; set; }

        /// <summary>
        /// Gets or sets a decimal value for the NetTaxableEarnings column.
        /// </summary>
        [DataMember]
        public decimal NetTaxableEarnings { get; set; }

        /// <summary>
        /// Gets or sets a decimal value for the MortgageRelief column.
        /// </summary>
        [DataMember]
        public decimal MortgageRelief { get; set; }

        /// <summary>
        /// Gets or sets a decimal value for the InsuranceRelief column.
        /// </summary>
        [DataMember]
        public decimal InsuranceRelief { get; set; }

        /// <summary>
        /// Gets or sets a decimal value for the GrossTax column.
        /// </summary>
        [DataMember]
        public decimal GrossTax { get; set; }

        /// <summary>
        /// Gets or sets a decimal value for the PersonalRelief column.
        /// </summary>
        [DataMember]
        public decimal PersonalRelief { get; set; }

        /// <summary>
        /// Gets or sets a decimal value for the PensionEmployer column.
        /// </summary>
        [DataMember]
        public decimal PensionEmployer { get; set; }

        /// <summary>
        /// Gets or sets a decimal value for the EmployerNSSF column.
        /// </summary>
        [DataMember]
        public decimal EmployerNSSF { get; set; }

        /// <summary>
        /// Gets or sets a decimal value for the PensionEmployee column.
        /// </summary>
        [DataMember]
        public decimal PensionEmployee { get; set; }

        /// <summary>
        /// Gets or sets a string value for the BankBranch column.
        /// </summary>
        [DataMember]
        public string BankBranch { get; set; }

        /// <summary>
        /// Gets or sets a string value for the Account column.
        /// </summary>
        [DataMember]
        public string Account { get; set; }

        /// <summary>
        /// Gets or sets a decimal value for the NSSF column.
        /// </summary>
        [DataMember]
        public decimal NSSF { get; set; }

        /// <summary>
        /// Gets or sets a decimal value for the NHIF column.
        /// </summary>
        [DataMember]
        public decimal NHIF { get; set; }

        /// <summary>
        /// Gets or sets a decimal value for the NetPay column.
        /// </summary>
        [DataMember]
        public decimal NetPay { get; set; }
    }
}
