//====================================================================================================
// Base code generated with Inertia: BE Gen (Build 2.5.5049.15162)
// Layered Architecture Solution Guidance (http://layerguidance.codeplex.com)
//
// Generated by Administrator at SAPSERVER on 12/31/2014 17:24:16 
//====================================================================================================

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Linq;
using System.Runtime.Serialization;


namespace SBiPayrollWeb.Entities
{
    /// <summary>
    /// Represents a row of PayslipDet_Temp data.
    /// </summary>
    [Serializable]
    [DataContract]
    public partial class PayslipDet_Temp
    {
        /// <summary>
        /// Gets or sets a int value for the Id column.
        /// </summary>
        [DataMember]
        [Browsable(false)]
        public int Id { get; set; }

        /// <summary>
        /// Gets or sets a string value for the EmpNo column.
        /// </summary>
        [DataMember]
        public string EmpNo { get; set; }

        /// <summary>
        /// Gets or sets a int value for the EmployeeId column.
        /// </summary>
        [DataMember]
        public int EmployeeId { get; set; }

        /// <summary>
        /// Gets or sets a int value for the EmpTxnId column.
        /// </summary>
        [DataMember]
        public int EmpTxnId { get; set; }

        /// <summary>
        /// Gets or sets a int value for the Period column.
        /// </summary>
        [DataMember]
        public int Period { get; set; }

        /// <summary>
        /// Gets or sets a int value for the Year column.
        /// </summary>
        [DataMember]
        public int Year { get; set; }

        /// <summary>
        /// Gets or sets a string value for the Description column.
        /// </summary>
        [DataMember]
        public string Description { get; set; }

        /// <summary>
        /// Gets or sets a string value for the TaxTracking column.
        /// </summary>
        [DataMember]
        public string TaxTracking { get; set; }

        /// <summary>
        /// Gets or sets a decimal value for the Amount column.
        /// </summary>
        [DataMember]
        public decimal Amount { get; set; }

        /// <summary>
        /// Gets or sets a string value for the DEType column.
        /// </summary>
        [DataMember]
        public string DEType { get; set; }

        /// <summary>
        /// Gets or sets a bool value for the IsStatutory column.
        /// </summary>
        [DataMember]
        public bool IsStatutory { get; set; }

        /// <summary>
        /// Gets or sets a bool value for the ShowInPayslip column.
        /// </summary>
        [DataMember]
        public bool ShowInPayslip { get; set; }

        /// <summary>
        /// Gets or sets a decimal value for the YTD column.
        /// </summary>
        [DataMember]
        public decimal YTD { get; set; }
    }
}
