//====================================================================================================
// Base code generated with Inertia: BE Gen (Build 2.5.5049.15162)
// Layered Architecture Solution Guidance (http://layerguidance.codeplex.com)
//
// Generated by Administrator at SAPSERVER on 12/31/2014 17:24:16 
//====================================================================================================

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System.Linq;
using System.Runtime.Serialization;


namespace SBiPayrollWeb.Entities
{
    /// <summary>
    /// Represents a row of TransactionDef data.
    /// </summary>
    [Serializable]
    [DataContract]
    public partial class TransactionDef
    {
        /// <summary>
        /// Gets or sets a string value for the TxnCode column.
        /// </summary>
        [DataMember]
        [Browsable(false)]
        public string TxnCode { get; set; }

        /// <summary>
        /// Gets or sets a char value for the DataEntry column.
        /// </summary>
        [DataMember]
        public char DataEntry { get; set; }

        /// <summary>
        /// Gets or sets a string value for the PayrollItem column.
        /// </summary>
        [DataMember]
        public string PayrollItem { get; set; }

        /// <summary>
        /// Gets or sets a decimal value for the DefaultAmount column.
        /// </summary>
        [DataMember]
        public decimal DefaultAmount { get; set; }

        /// <summary>
        /// Gets or sets a bool value for the Enabled column.
        /// </summary>
        [DataMember]
        public bool Enabled { get; set; }

        /// <summary>
        /// Gets or sets a bool value for the Recurrent column.
        /// </summary>
        [DataMember]
        public bool Recurrent { get; set; }

        /// <summary>
        /// Gets or sets a bool value for the TrackYTD column.
        /// </summary>
        [DataMember]
        public bool TrackYTD { get; set; }
    }
}
