//====================================================================================================
// Base code generated with Momentum: DAC Gen (Build 2.5.5049.15162)
// Layered Architecture Solution Guidance (http://layerguidance.codeplex.com)
//
// Generated by Administrator at SAPSERVER on 12/31/2014 17:33:56 
//====================================================================================================

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Text;
using System.Data;
using System.Data.Common;
using Microsoft.Practices.EnterpriseLibrary.Data;
using SBiPayrollWeb.Entities;

namespace SBiPayrollWeb.Data
{
    /// <summary>
    /// NHIFRates data access component. Manages CRUD operations for the NHIFRates table.
    /// </summary>
    public partial class NHIFRateDAC : DataAccessComponent
    {
        /// <summary>
        /// Inserts a new row in the NHIFRates table.
        /// </summary>
        /// <param name="nHIFRate">A NHIFRate object.</param>
        /// <returns>An updated NHIFRate object.</returns>
        public NHIFRate Create(NHIFRate nHIFRate)
        {
            const string SQL_STATEMENT =
                "INSERT INTO dbo.NHIFRates ([FromAmt], [ToAmt], [Rate]) " +
                "VALUES(@FromAmt, @ToAmt, @Rate); SELECT SCOPE_IDENTITY();";

            // Connect to database.
            Database db = DatabaseFactory.CreateDatabase(CONNECTION_NAME);
            using (DbCommand cmd = db.GetSqlStringCommand(SQL_STATEMENT))
            {
                // Set parameter values.
                db.AddInParameter(cmd, "@FromAmt", DbType.Currency, nHIFRate.FromAmt);
                db.AddInParameter(cmd, "@ToAmt", DbType.Currency, nHIFRate.ToAmt);
                db.AddInParameter(cmd, "@Rate", DbType.Currency, nHIFRate.Rate);

                // Get the primary key value.
                nHIFRate.Id = Convert.ToInt32(db.ExecuteScalar(cmd));
            }

            return nHIFRate;
        }

        /// <summary>
        /// Updates an existing row in the NHIFRates table.
        /// </summary>
        /// <param name="nHIFRate">A NHIFRate entity object.</param>
        public void UpdateById(NHIFRate nHIFRate)
        {
            const string SQL_STATEMENT =
                "UPDATE dbo.NHIFRates " +
                "SET " +
                    "[FromAmt]=@FromAmt, " +
                    "[ToAmt]=@ToAmt, " +
                    "[Rate]=@Rate " +
                "WHERE [Id]=@Id ";

            // Connect to database.
            Database db = DatabaseFactory.CreateDatabase(CONNECTION_NAME);
            using (DbCommand cmd = db.GetSqlStringCommand(SQL_STATEMENT))
            {
                // Set parameter values.
                db.AddInParameter(cmd, "@FromAmt", DbType.Currency, nHIFRate.FromAmt);
                db.AddInParameter(cmd, "@ToAmt", DbType.Currency, nHIFRate.ToAmt);
                db.AddInParameter(cmd, "@Rate", DbType.Currency, nHIFRate.Rate);
                db.AddInParameter(cmd, "@Id", DbType.Int32, nHIFRate.Id);

                db.ExecuteNonQuery(cmd);
            }
        }

        /// <summary>
        /// Conditionally deletes one or more rows in the NHIFRates table.
        /// </summary>
        /// <param name="id">A id value.</param>
        public void DeleteById(int id)
        {
            const string SQL_STATEMENT = "DELETE dbo.NHIFRates " +
                                         "WHERE [Id]=@Id ";

            // Connect to database.
            Database db = DatabaseFactory.CreateDatabase(CONNECTION_NAME);
            using (DbCommand cmd = db.GetSqlStringCommand(SQL_STATEMENT))
            {
                // Set parameter values.
                db.AddInParameter(cmd, "@Id", DbType.Int32, id);


                db.ExecuteNonQuery(cmd);
            }
        }

        /// <summary>
        /// Returns a row from the NHIFRates table.
        /// </summary>
        /// <param name="id">A Id value.</param>
        /// <returns>A NHIFRate object with data populated from the database.</returns>
        public NHIFRate SelectById(int id)
        {
            const string SQL_STATEMENT =
                "SELECT [Id], [FromAmt], [ToAmt], [Rate] " +
                "FROM dbo.NHIFRates  " +
                "WHERE [Id]=@Id ";

            NHIFRate nHIFRate = null;

            // Connect to database.
            Database db = DatabaseFactory.CreateDatabase(CONNECTION_NAME);
            using (DbCommand cmd = db.GetSqlStringCommand(SQL_STATEMENT))
            {
                db.AddInParameter(cmd, "@Id", DbType.Int32, id);

                using (IDataReader dr = db.ExecuteReader(cmd))
                {
                    if (dr.Read())
                    {
                        // Create a new NHIFRate
                        nHIFRate = new NHIFRate();

                        // Read values.
                        nHIFRate.Id = base.GetDataValue<int>(dr, "Id");
                        nHIFRate.FromAmt = base.GetDataValue<decimal>(dr, "FromAmt");
                        nHIFRate.ToAmt = base.GetDataValue<decimal>(dr, "ToAmt");
                        nHIFRate.Rate = base.GetDataValue<decimal>(dr, "Rate");
                    }
                }
            }

            return nHIFRate;
        }

        /// <summary>
        /// Conditionally retrieves one or more rows from the NHIFRates table.
        /// </summary>
        /// <returns>A collection of NHIFRate objects.</returns>		
        public List<NHIFRate> Select()
        {
            // WARNING! The following SQL query does not contain a WHERE condition.
            // You are advised to include a WHERE condition to prevent any performance
            // issues when querying large resultsets.
            const string SQL_STATEMENT =
                "SELECT [Id], [FromAmt], [ToAmt], [Rate] " +
                "FROM dbo.NHIFRates ";

            List<NHIFRate> result = new List<NHIFRate>();

            // Connect to database.
            Database db = DatabaseFactory.CreateDatabase(CONNECTION_NAME);
            using (DbCommand cmd = db.GetSqlStringCommand(SQL_STATEMENT))
            {
                using (IDataReader dr = db.ExecuteReader(cmd))
                {
                    while (dr.Read())
                    {
                        // Create a new NHIFRate
                        NHIFRate nHIFRate = new NHIFRate();

                        // Read values.
                        nHIFRate.Id = base.GetDataValue<int>(dr, "Id");
                        nHIFRate.FromAmt = base.GetDataValue<decimal>(dr, "FromAmt");
                        nHIFRate.ToAmt = base.GetDataValue<decimal>(dr, "ToAmt");
                        nHIFRate.Rate = base.GetDataValue<decimal>(dr, "Rate");

                        // Add to List.
                        result.Add(nHIFRate);
                    }
                }
            }

            return result;
        }
    }
}

