//====================================================================================================
// Base code generated with Momentum: DAC Gen (Build 2.5.5049.15162)
// Layered Architecture Solution Guidance (http://layerguidance.codeplex.com)
//
// Generated by Administrator at SAPSERVER on 12/31/2014 17:33:56 
//====================================================================================================

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Text;
using System.Data;
using System.Data.Common;
using Microsoft.Practices.EnterpriseLibrary.Data;
using SBiPayrollWeb.Entities;

namespace SBiPayrollWeb.Data
{
    /// <summary>
    /// TaxTracking data access component. Manages CRUD operations for the TaxTracking table.
    /// </summary>
    public partial class TaxTrackingDAC : DataAccessComponent
    {
        /// <summary>
        /// Inserts a new row in the TaxTracking table.
        /// </summary>
        /// <param name="taxTracking">A TaxTracking object.</param>
        /// <returns>An updated TaxTracking object.</returns>
        public TaxTracking Create(TaxTracking taxTracking)
        {
            const string SQL_STATEMENT =
                "INSERT INTO dbo.TaxTracking ([Id], [Description]) " +
                "VALUES(@Id, @Description);  ";

            // Connect to database.
            Database db = DatabaseFactory.CreateDatabase(CONNECTION_NAME);
            using (DbCommand cmd = db.GetSqlStringCommand(SQL_STATEMENT))
            {
                // Set parameter values.
                db.AddInParameter(cmd, "@Id", DbType.String, taxTracking.Id);
                db.AddInParameter(cmd, "@Description", DbType.String, taxTracking.Description);

                db.ExecuteNonQuery(cmd);
            }

            return taxTracking;
        }

        /// <summary>
        /// Updates an existing row in the TaxTracking table.
        /// </summary>
        /// <param name="taxTracking">A TaxTracking entity object.</param>
        public void UpdateById(TaxTracking taxTracking)
        {
            const string SQL_STATEMENT =
                "UPDATE dbo.TaxTracking " +
                "SET " +
                    "[Description]=@Description " +
                "WHERE [Id]=@Id ";

            // Connect to database.
            Database db = DatabaseFactory.CreateDatabase(CONNECTION_NAME);
            using (DbCommand cmd = db.GetSqlStringCommand(SQL_STATEMENT))
            {
                // Set parameter values.
                db.AddInParameter(cmd, "@Description", DbType.String, taxTracking.Description);
                db.AddInParameter(cmd, "@Id", DbType.String, taxTracking.Id);

                db.ExecuteNonQuery(cmd);
            }
        }

        /// <summary>
        /// Conditionally deletes one or more rows in the TaxTracking table.
        /// </summary>
        /// <param name="id">A id value.</param>
        public void DeleteById(string id)
        {
            const string SQL_STATEMENT = "DELETE dbo.TaxTracking " +
                                         "WHERE [Id]=@Id ";

            // Connect to database.
            Database db = DatabaseFactory.CreateDatabase(CONNECTION_NAME);
            using (DbCommand cmd = db.GetSqlStringCommand(SQL_STATEMENT))
            {
                // Set parameter values.
                db.AddInParameter(cmd, "@Id", DbType.String, id);


                db.ExecuteNonQuery(cmd);
            }
        }

        /// <summary>
        /// Returns a row from the TaxTracking table.
        /// </summary>
        /// <param name="id">A Id value.</param>
        /// <returns>A TaxTracking object with data populated from the database.</returns>
        public TaxTracking SelectById(string id)
        {
            const string SQL_STATEMENT =
                "SELECT [Id], [Description] " +
                "FROM dbo.TaxTracking  " +
                "WHERE [Id]=@Id ";

            TaxTracking taxTracking = null;

            // Connect to database.
            Database db = DatabaseFactory.CreateDatabase(CONNECTION_NAME);
            using (DbCommand cmd = db.GetSqlStringCommand(SQL_STATEMENT))
            {
                db.AddInParameter(cmd, "@Id", DbType.String, id);

                using (IDataReader dr = db.ExecuteReader(cmd))
                {
                    if (dr.Read())
                    {
                        // Create a new TaxTracking
                        taxTracking = new TaxTracking();

                        // Read values.
                        taxTracking.Id = base.GetDataValue<string>(dr, "Id");
                        taxTracking.Description = base.GetDataValue<string>(dr, "Description");
                    }
                }
            }

            return taxTracking;
        }

        /// <summary>
        /// Conditionally retrieves one or more rows from the TaxTracking table.
        /// </summary>
        /// <returns>A collection of TaxTracking objects.</returns>		
        public List<TaxTracking> Select()
        {
            // WARNING! The following SQL query does not contain a WHERE condition.
            // You are advised to include a WHERE condition to prevent any performance
            // issues when querying large resultsets.
            const string SQL_STATEMENT =
                "SELECT [Id], [Description] " +
                "FROM dbo.TaxTracking ";

            List<TaxTracking> result = new List<TaxTracking>();

            // Connect to database.
            Database db = DatabaseFactory.CreateDatabase(CONNECTION_NAME);
            using (DbCommand cmd = db.GetSqlStringCommand(SQL_STATEMENT))
            {
                using (IDataReader dr = db.ExecuteReader(cmd))
                {
                    while (dr.Read())
                    {
                        // Create a new TaxTracking
                        TaxTracking taxTracking = new TaxTracking();

                        // Read values.
                        taxTracking.Id = base.GetDataValue<string>(dr, "Id");
                        taxTracking.Description = base.GetDataValue<string>(dr, "Description");

                        // Add to List.
                        result.Add(taxTracking);
                    }
                }
            }

            return result;
        }
    }
}

