//====================================================================================================
// Base code generated with Momentum: DAC Gen (Build 2.5.5049.15162)
// Layered Architecture Solution Guidance (http://layerguidance.codeplex.com)
//
// Generated by Administrator at SAPSERVER on 12/31/2014 17:33:56 
//====================================================================================================

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Text;
using System.Data;
using System.Data.Common;
using Microsoft.Practices.EnterpriseLibrary.Data;
using SBiPayrollWeb.Entities;

namespace SBiPayrollWeb.Data
{
    /// <summary>
    /// Transactions data access component. Manages CRUD operations for the Transactions table.
    /// </summary>
    public partial class TransactionDAC : DataAccessComponent
    {
        /// <summary>
        /// Inserts a new row in the Transactions table.
        /// </summary>
        /// <param name="transaction">A Transaction object.</param>
        /// <returns>An updated Transaction object.</returns>
        public Transaction Create(Transaction transaction)
        {
            const string SQL_STATEMENT =
                "INSERT INTO dbo.Transactions ([PostDate], [Amount], [DRCR], [Narrative], [TxnType]) " +
                "VALUES(@PostDate, @Amount, @DRCR, @Narrative, @TxnType); SELECT SCOPE_IDENTITY();";

            // Connect to database.
            Database db = DatabaseFactory.CreateDatabase(CONNECTION_NAME);
            using (DbCommand cmd = db.GetSqlStringCommand(SQL_STATEMENT))
            {
                // Set parameter values.
                db.AddInParameter(cmd, "@PostDate", DbType.DateTime, transaction.PostDate);
                db.AddInParameter(cmd, "@Amount", DbType.Currency, transaction.Amount);
                db.AddInParameter(cmd, "@DRCR", DbType.StringFixedLength, transaction.DRCR);
                db.AddInParameter(cmd, "@Narrative", DbType.String, transaction.Narrative);
                db.AddInParameter(cmd, "@TxnType", DbType.Int32, transaction.TxnType);

                // Get the primary key value.
                transaction.Id = Convert.ToInt32(db.ExecuteScalar(cmd));
            }

            return transaction;
        }

        /// <summary>
        /// Updates an existing row in the Transactions table.
        /// </summary>
        /// <param name="transaction">A Transaction entity object.</param>
        public void UpdateById(Transaction transaction)
        {
            const string SQL_STATEMENT =
                "UPDATE dbo.Transactions " +
                "SET " +
                    "[PostDate]=@PostDate, " +
                    "[Amount]=@Amount, " +
                    "[DRCR]=@DRCR, " +
                    "[Narrative]=@Narrative, " +
                    "[TxnType]=@TxnType " +
                "WHERE [Id]=@Id ";

            // Connect to database.
            Database db = DatabaseFactory.CreateDatabase(CONNECTION_NAME);
            using (DbCommand cmd = db.GetSqlStringCommand(SQL_STATEMENT))
            {
                // Set parameter values.
                db.AddInParameter(cmd, "@PostDate", DbType.DateTime, transaction.PostDate);
                db.AddInParameter(cmd, "@Amount", DbType.Currency, transaction.Amount);
                db.AddInParameter(cmd, "@DRCR", DbType.StringFixedLength, transaction.DRCR);
                db.AddInParameter(cmd, "@Narrative", DbType.String, transaction.Narrative);
                db.AddInParameter(cmd, "@TxnType", DbType.Int32, transaction.TxnType);
                db.AddInParameter(cmd, "@Id", DbType.Int32, transaction.Id);

                db.ExecuteNonQuery(cmd);
            }
        }

        /// <summary>
        /// Conditionally deletes one or more rows in the Transactions table.
        /// </summary>
        /// <param name="id">A id value.</param>
        public void DeleteById(int id)
        {
            const string SQL_STATEMENT = "DELETE dbo.Transactions " +
                                         "WHERE [Id]=@Id ";

            // Connect to database.
            Database db = DatabaseFactory.CreateDatabase(CONNECTION_NAME);
            using (DbCommand cmd = db.GetSqlStringCommand(SQL_STATEMENT))
            {
                // Set parameter values.
                db.AddInParameter(cmd, "@Id", DbType.Int32, id);


                db.ExecuteNonQuery(cmd);
            }
        }

        /// <summary>
        /// Returns a row from the Transactions table.
        /// </summary>
        /// <param name="id">A Id value.</param>
        /// <returns>A Transaction object with data populated from the database.</returns>
        public Transaction SelectById(int id)
        {
            const string SQL_STATEMENT =
                "SELECT [Id], [PostDate], [Amount], [DRCR], [Narrative], [TxnType] " +
                "FROM dbo.Transactions  " +
                "WHERE [Id]=@Id ";

            Transaction transaction = null;

            // Connect to database.
            Database db = DatabaseFactory.CreateDatabase(CONNECTION_NAME);
            using (DbCommand cmd = db.GetSqlStringCommand(SQL_STATEMENT))
            {
                db.AddInParameter(cmd, "@Id", DbType.Int32, id);

                using (IDataReader dr = db.ExecuteReader(cmd))
                {
                    if (dr.Read())
                    {
                        // Create a new Transaction
                        transaction = new Transaction();

                        // Read values.
                        transaction.Id = base.GetDataValue<int>(dr, "Id");
                        transaction.PostDate = base.GetDataValue<DateTime>(dr, "PostDate");
                        transaction.Amount = base.GetDataValue<decimal>(dr, "Amount");
                        transaction.DRCR = base.GetDataValue<string>(dr, "DRCR");
                        transaction.Narrative = base.GetDataValue<string>(dr, "Narrative");
                        transaction.TxnType = base.GetDataValue<int>(dr, "TxnType");
                    }
                }
            }

            return transaction;
        }

        /// <summary>
        /// Conditionally retrieves one or more rows from the Transactions table.
        /// </summary>
        /// <returns>A collection of Transaction objects.</returns>		
        public List<Transaction> Select()
        {
            // WARNING! The following SQL query does not contain a WHERE condition.
            // You are advised to include a WHERE condition to prevent any performance
            // issues when querying large resultsets.
            const string SQL_STATEMENT =
                "SELECT [Id], [PostDate], [Amount], [DRCR], [Narrative], [TxnType] " +
                "FROM dbo.Transactions ";

            List<Transaction> result = new List<Transaction>();

            // Connect to database.
            Database db = DatabaseFactory.CreateDatabase(CONNECTION_NAME);
            using (DbCommand cmd = db.GetSqlStringCommand(SQL_STATEMENT))
            {
                using (IDataReader dr = db.ExecuteReader(cmd))
                {
                    while (dr.Read())
                    {
                        // Create a new Transaction
                        Transaction transaction = new Transaction();

                        // Read values.
                        transaction.Id = base.GetDataValue<int>(dr, "Id");
                        transaction.PostDate = base.GetDataValue<DateTime>(dr, "PostDate");
                        transaction.Amount = base.GetDataValue<decimal>(dr, "Amount");
                        transaction.DRCR = base.GetDataValue<string>(dr, "DRCR");
                        transaction.Narrative = base.GetDataValue<string>(dr, "Narrative");
                        transaction.TxnType = base.GetDataValue<int>(dr, "TxnType");

                        // Add to List.
                        result.Add(transaction);
                    }
                }
            }

            return result;
        }
    }
}

