//====================================================================================================
// Base code generated with Motion: BC Gen (Build 2.2.5049.15162)
// Layered Architecture Solution Guidance (http://layerguidance.codeplex.com)
//
// Generated by Administrator at SAPSERVER on 06/12/2014 09:07:04 
//====================================================================================================

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using SBiPayrollWeb.Entities;
using SBiPayrollWeb.Data;


namespace SBiPayrollWeb.Business
{
    /// <summary>
    /// Banks business component.
    /// </summary>
    public partial class BanksComponent
    {
        /// <summary>
        /// GetAllBanks business method. 
        /// </summary>
        /// <returns>Returns a List<Bank> object.</returns>
        public List<Bank> GetAllBanks()
        {
            List<Bank> result = default(List<Bank>);

            // Data access component declarations.
            BankDAC bankDAC = new BankDAC();

            // Step 1 - Calling Select on BankDAC.
            result = bankDAC.Select();
            return result;

        }

        /// <summary>
        /// GetBank business method. 
        /// </summary>
        /// <param name="bankCode">A bankCode value.</param>
        /// <returns>Returns a Bank object.</returns>
        public Bank GetBankById(string bankCode)
        {
            Bank result = default(Bank);

            // Data access component declarations.
            BankDAC bankDAC = new BankDAC();

            // Step 1 - Calling SelectById on BankDAC.
            result = bankDAC.SelectById(bankCode);
            return result;

        }

        /// <summary>
        /// CreateBank business method. 
        /// </summary>
        /// <param name="bank">A bank value.</param>
        /// <returns>Returns a Bank object.</returns>
        public Bank CreateBank(Bank bank)
        {
            Bank result = default(Bank);

            // Data access component declarations.
            BankDAC bankDAC = new BankDAC();

            // Step 1 - Calling Create on BankDAC.
            result = bankDAC.Create(bank);
            return result;

        }

        /// <summary>
        /// UpdateBank business method. 
        /// </summary>
        /// <param name="bank">A bank value.</param>
        public void UpdateBank(Bank bank)
        {
            // Data access component declarations.
            BankDAC bankDAC = new BankDAC();

            // Step 1 - Calling UpdateById on BankDAC.
            bankDAC.UpdateById(bank);

        }

        /// <summary>
        /// DeleteBank business method. 
        /// </summary>
        /// <param name="bankCode">A bankCode value.</param>
        public void DeleteBankById(string bankCode)
        {
            // Data access component declarations.
            BankDAC bankDAC = new BankDAC();

            // Step 1 - Calling DeleteById on BankDAC.
            bankDAC.DeleteById(bankCode);

        }
    }
}
