//====================================================================================================
// Base code generated with Motion: BC Gen (Build 2.2.5049.15162)
// Layered Architecture Solution Guidance (http://layerguidance.codeplex.com)
//
// Generated by Administrator at SAPSERVER on 06/12/2014 09:07:04 
//====================================================================================================

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using SBiPayrollWeb.Entities;
using SBiPayrollWeb.Data;


namespace SBiPayrollWeb.Business
{
    /// <summary>
    /// Benefits business component.
    /// </summary>
    public partial class BenefitsComponent
    {
        /// <summary>
        /// GetAllBenefits business method. 
        /// </summary>
        /// <returns>Returns a List<Benefit> object.</returns>
        public List<Benefit> GetAllBenefits()
        {
            List<Benefit> result = default(List<Benefit>);

            // Data access component declarations.
            BenefitDAC benefitDAC = new BenefitDAC();

            // Step 1 - Calling Select on BenefitDAC.
            result = benefitDAC.Select();
            return result;

        }

        /// <summary>
        /// GetBenefit business method. 
        /// </summary>
        /// <param name="id">A id value.</param>
        /// <returns>Returns a Benefit object.</returns>
        public Benefit GetBenefitById(int id)
        {
            Benefit result = default(Benefit);

            // Data access component declarations.
            BenefitDAC benefitDAC = new BenefitDAC();

            // Step 1 - Calling SelectById on BenefitDAC.
            result = benefitDAC.SelectById(id);
            return result;

        }

        /// <summary>
        /// CreateBenefit business method. 
        /// </summary>
        /// <param name="benefit">A benefit value.</param>
        /// <returns>Returns a Benefit object.</returns>
        public Benefit CreateBenefit(Benefit benefit)
        {
            Benefit result = default(Benefit);

            // Data access component declarations.
            BenefitDAC benefitDAC = new BenefitDAC();

            // Step 1 - Calling Create on BenefitDAC.
            result = benefitDAC.Create(benefit);
            return result;

        }

        /// <summary>
        /// UpdateBenefit business method. 
        /// </summary>
        /// <param name="benefit">A benefit value.</param>
        public void UpdateBenefit(Benefit benefit)
        {
            // Data access component declarations.
            BenefitDAC benefitDAC = new BenefitDAC();

            // Step 1 - Calling UpdateById on BenefitDAC.
            benefitDAC.UpdateById(benefit);

        }

        /// <summary>
        /// DeleteBenefit business method. 
        /// </summary>
        /// <param name="id">A id value.</param>
        public void DeleteBenefitById(int id)
        {
            // Data access component declarations.
            BenefitDAC benefitDAC = new BenefitDAC();

            // Step 1 - Calling DeleteById on BenefitDAC.
            benefitDAC.DeleteById(id);

        }
    }
}
