//====================================================================================================
// Base code generated with Motion: BC Gen (Build 2.2.5049.15162)
// Layered Architecture Solution Guidance (http://layerguidance.codeplex.com)
//
// Generated by Administrator at SAPSERVER on 06/12/2014 07:27:12 
//====================================================================================================

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using SBiPayrollWeb.Entities;
using SBiPayrollWeb.Data;


namespace SBiPayrollWeb.Business
{
    /// <summary>
    /// Payrolls business component.
    /// </summary>
    public partial class PayrollsComponent
    {
        /// <summary>
        /// GetPayrolls business method. 
        /// </summary>
        /// <returns>Returns a List<Payroll> object.</returns>
        public List<Payroll> GetAllPayrolls()
        {
            List<Payroll> result = default(List<Payroll>);

            // Data access component declarations.
            PayrollDAC payrollDAC = new PayrollDAC();

            // Step 1 - Calling Select on PayrollDAC.
            result = payrollDAC.Select();
            return result;

        }

        /// <summary>
        /// CreatePayroll business method. 
        /// </summary>
        /// <param name="payroll">A payroll value.</param>
        /// <returns>Returns a Payroll object.</returns>
        public Payroll CreatePayroll(Payroll payroll)
        {
            Payroll result = default(Payroll);

            // Data access component declarations.
            PayrollDAC payrollDAC = new PayrollDAC();

            // Step 1 - Calling Create on PayrollDAC.
            result = payrollDAC.Create(payroll);
            return result;

        }

        /// <summary>
        /// DeletePayroll business method. 
        /// </summary>
        /// <param name="period">A period value.</param>
        public void DeletePayroll(int period)
        {
            // Data access component declarations.
            PayrollDAC payrollDAC = new PayrollDAC();

            // Step 1 - Calling DeleteById on PayrollDAC.
            payrollDAC.DeleteById(period);

        }

        /// <summary>
        /// UpdatePayroll business method. 
        /// </summary>
        /// <param name="payroll">A payroll value.</param>
        public void UpdatePayroll(Payroll payroll)
        {
            // Data access component declarations.
            PayrollDAC payrollDAC = new PayrollDAC();

            // Step 1 - Calling UpdateById on PayrollDAC.
            payrollDAC.UpdateById(payroll);

        }

        /// <summary>
        /// GetPayroll business method. 
        /// </summary>
        /// <param name="period">A period value.</param>
        /// <param name="year">A year value.</param>
        /// <returns>Returns a Payroll object.</returns>
        public Payroll GetPayroll(int period, int year)
        {
            Payroll result = default(Payroll);

            // Data access component declarations.
            PayrollDAC payrollDAC = new PayrollDAC();

            // Step 1 - Calling SelectById on PayrollDAC.
            result = payrollDAC.SelectById(period, year);
            return result;

        }
    }
}
