//====================================================================================================
// Base code generated with Motion: BC Gen (Build 2.2.5049.15162)
// Layered Architecture Solution Guidance (http://layerguidance.codeplex.com)
//
// Generated by Administrator at SAPSERVER on 06/12/2014 08:33:44 
//====================================================================================================

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using SBiPayrollWeb.Entities;
using SBiPayrollWeb.Data;


namespace SBiPayrollWeb.Business
{
    /// <summary>
    /// PayrollItems business component.
    /// </summary>
    public partial class PayrollItemsComponent
    {
        /// <summary>
        /// GetAllPayrollItems business method. 
        /// </summary>
        /// <returns>Returns a List<PayrollItem> object.</returns>
        public List<PayrollItem> GetAllPayrollItems()
        {
            List<PayrollItem> result = default(List<PayrollItem>);

            // Data access component declarations.
            PayrollItemDAC payrollItemDAC = new PayrollItemDAC();

            // Step 1 - Calling Select on PayrollItemDAC.
            result = payrollItemDAC.Select();
            return result;

        }

        /// <summary>
        /// GetPayrollItem business method. 
        /// </summary>
        /// <param name="id">A id value.</param>
        /// <returns>Returns a PayrollItem object.</returns>
        public PayrollItem GetPayrollItemById(string id)
        {
            PayrollItem result = default(PayrollItem);

            // Data access component declarations.
            PayrollItemDAC payrollItemDAC = new PayrollItemDAC();

            // Step 1 - Calling SelectById on PayrollItemDAC.
            result = payrollItemDAC.SelectById(id);
            return result;

        }

        /// <summary>
        /// CreatePayrollItem business method. 
        /// </summary>
        /// <param name="payrollItem">A payrollItem value.</param>
        /// <returns>Returns a PayrollItem object.</returns>
        public PayrollItem CreatePayrollItem(PayrollItem payrollItem)
        {
            PayrollItem result = default(PayrollItem);

            // Data access component declarations.
            PayrollItemDAC payrollItemDAC = new PayrollItemDAC();

            // Step 1 - Calling Create on PayrollItemDAC.
            result = payrollItemDAC.Create(payrollItem);
            return result;

        }

        /// <summary>
        /// DeletePayrollItem business method. 
        /// </summary>
        /// <param name="id">A id value.</param>
        public void DeletePayrollItemById(string id)
        {
            // Data access component declarations.
            PayrollItemDAC payrollItemDAC = new PayrollItemDAC();

            // Step 1 - Calling DeleteById on PayrollItemDAC.
            payrollItemDAC.DeleteById(id);

        }

        /// <summary>
        /// UpdatePayrollItem business method. 
        /// </summary>
        /// <param name="payrollItem">A payrollItem value.</param>
        public void UpdatePayrollItem(PayrollItem payrollItem)
        {
            // Data access component declarations.
            PayrollItemDAC payrollItemDAC = new PayrollItemDAC();

            // Step 1 - Calling UpdateById on PayrollItemDAC.
            payrollItemDAC.UpdateById(payrollItem);

        }
    }
}
